using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sitecore.Data.Items;
using TweetSharp;
using Fortis.Model;
using SitecorePlay.Model.Autogenerated;

namespace SitecorePlay.Web.Helpers
{
    public class TwitterHelper
    {
        private string ConsumerKey { get; set; }

        private string ConsumerSecret { get; set; }

        private string AccessToken { get; set; }

        private string AccessTokenSecret { get; set; }

        public string ScreenName { get; set; }

        public string NoOfFeeds { get; set; }

        private readonly IItemFactory _itemFactory;

        public TwitterHelper(IItemFactory itemFactory)
        {
            _itemFactory = itemFactory;
        }

        public void Run()
        {
            IItemWrapper context = _itemFactory.GetContextItem<IItemWrapper>();
        }
        public TwitterService GetTwitterService()
        {
            //var ScreenName = RenderingContext.Current.Rendering.Parameters["ScreenName"];
            //var NoOfFeeds = RenderingContext.Current.Rendering.Parameters["NoOfFeeds"];

           // Item[] items = Sitecore.Context.Database.SelectItems("/sitecore/system/Modules/TwitterFeed/TwitterFeedSettings");
            //IItemWrapper item = this._itemFactory.Select<IItemWrapper>("/sitecore/system/Sitecore Play/TwitterSettings");

           // IItemWrapper contextItem = this._itemFactory.GetContextItem<ITwitterSettings>();

            var contextItem = _itemFactory.GetRenderingContextItems<ITwitterSettings, ITwitterSettings>();

            ConsumerKey = contextItem.RenderingItem.ConsumerKeyValue;
            ConsumerSecret = contextItem.RenderingItem.ConsumerSecretValue;
            AccessToken = contextItem.RenderingItem.AccessTokenValue;
            AccessTokenSecret = contextItem.RenderingItem.AccessTokenSecretValue;
            ScreenName = contextItem.RenderingItem.ScreenNameValue;
            NoOfFeeds = contextItem.RenderingItem.NoOfFeedsValue.ToString();
            

            var service = new TwitterService(ConsumerKey, ConsumerSecret, AccessToken, AccessTokenSecret);
            return service;
        }
    }
}